### ISSUE TITLE
Some questions about paper

### ISSUE THREAD

**Issue by Ostnie** [jwehrmann/chain-vse#1]
Hi, I’m glad to find your code in here, I have read your paper before, but still have some question about it. The question may be simpler because I am a beginner, both in English and Deeplearning.
1.	**What is the Bidirectional mean in your title?**
I only know some things about bidirectional RNN, In my view, Bidirectional means that we should have two starting and ending points, but I didn’t find them in your paper or network.
2.	**In section 2.2, you said we can divide the 7*7 convolution kernel into two 7 convolution kernels, I don’t know whether my understand is correct.**
It is hard for me to understand it’s convolution process, I know how the n*n kernels work, and I also understand the Figure 2 you showed. As I know, when we use a n*n kernel, we can get the relationship around the center. If we only use n, I think we can only get the information about row or col, Is my understand correct? If so, that means we can process the row and column information separately and combine them.
3.	**What is the relationship between CHAIN-VSE-v1 and CHAIN-VSE-v2?** 
In paper I see you said v2 is the lighter version of v1, Is it means that all structures are the same, we only changed the Convolution kernel from N*N to two N kernels ?
My next step is to read your code to deepen my understanding of the paper. Then maybe I will have new questions I hope you will not hate me ..
Many thanks!

**Comment by jwehrmann** [comment]
Hi, Ostnie! Sorry for the late reply.

1. The bidirectional in the title refers to the task of bidirectional retrieval of images and captions, also known as multimodal retrieval, cross-modal retrieval, and others. It is bidirectional because we can retrieve captions given images and retrieve images given captions. In the paper we focus in the text encoding strategy, but indeed we have two network inputs (images and captions). 

2. Note that our filters are not 7 x 7 x C (channels from previous layer), they are 7 X C because the input data is text (1D data). We replace standard 1D convolutions by depth-wise separable ones, i.e., we first perform a convolution through the temporal dimension in each channel separately, and we merge the channel information by using a regular 1 x C conv layer. 

3. Yes, you are right: v2 is lighter mostly because of the separable convolutional layers. However, note that v2 does not achieve top results. So, I would recommend for you to use v1 instead. 

Feel free to contact me via e-mail in case of additional doubts.
